apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: mck510-dev
data:
  SERVER_URL: "http://127.0.0.1:3000"
  CLOUDANT_URL: "https://3c9b2c48-06e8-4bb9-b963-3bd0b7d1dbff-bluemix.cloudant.com"
  CLOUDANT_DB_NAME: "todo-db"
